--- 

- name: Secure ssh 
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: "sshd -t -f %s"
  with_items:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^PubkeyAuthentication"
      line: "PubkeyAuthentication yes"
    - regexp: "^PermitEmptyPasswords"
      line: "PermitEmptyPasswords no"
  when: ansible_os_family == "Debian" 
  
- name: Insuring Secure ssh works
  file: 
    path: /etc/ssh/sshd_config.d/50-cloud-init.conf
    state: absent

  notify: restart ssh
