---
- name: Update machines for Debian 
  apt:
    update_cache: yes
    name: "*"
    state: latest
    autoremove: yes
  when: ansible_os_family == "Debian" 
  tags: update
  notify: reboot
  
- name: Update machines for RHEL
  yum: 
    update_cache: yes
    name: "*"
    state: latest
  when: ansible_os_family == "RedHat"
  tags: update
  #notify: reboot