---

- name: Install debian packages
  apt:
    name:
      - docker.io
      - docker-compose
      - fail2ban
      - git 
      - wget 
      - curl
      - vim 
    state: present
  notify: enable_service


- name: cloudfalred Install
  block:
    - name: Check cloudfalred Install
      command: dpkg-query -W cloudfalred
      register: cloudfalre
      failed_when: cloudfalre.rc > 1
      changed_when: cloudfalre.rc == 1
    
    - name: Install cloudfalred
      apt: deb="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb"
      become: true
      when: cloudfalre.rc == 1